wallpaper {
    monitor = Unknown-1
    path = /home/solar/Downloads/0-dot-hands.webp
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/solar/Downloads/0-dot-hands.webp
    fit_mode = cover
}

ipc = on
splash = false

