general {
    lock_cmd = pamixer -m    
    unlock_cmd = pamixer -u    
    before_sleep_cmd = hyprlock
}

# This turns off the screen before locking the screen. I prefer to not use it. Uncomment if you want it.
# listener {
#     timeout = 150
#     on_timeout = hyprctl dispatch dpms off
#     on_resume = hyprctl dispatch dpms on
# }

# Listener 2: Trigger the actual flat black lock screen
listener {
    timeout = 180                                 # 3 Minutes
    on-timeout = pamixer -m && hyprlock && pamixer -u
}
